### ISSUE TITLE
Invalid parameter show_diff

### ISSUE THREAD

**Issue by CarmenAPuccio** [justindowning/puppet-awscli#40]
I'm trying to test out your module and I can't get it to run. I'm making a simple class and running it inside vagrant (same box as your demo). Puppetfile is attached. Am I missing something?

config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box'

# == Class awsads
class awsads {

  notify{ "GOT TO THE CLASS":}

  include ::stdlib
  include ::awscli

  awscli::profile { 'default':
    user                  => 'root',
    aws_access_key_id     => 'ACCESSKEY',
    aws_secret_access_key => 'SECRETKEY',
    aws_region            => 'us-west-2'
 }
}

--------------PUPPETFILE----------

forge "https://forgeapi.puppetlabs.com"

mod 'stahnma/epel', :latest
mod 'puppetlabs/inifile', :latest
mod 'puppetlabs-stdlib'
mod 'jdowning-awscli'
mod 'puppetlabs-concat'

-------------------------------
=> default: Error: /Stage[main]/Awsads/Awscli::Profile[default]/Concat[/root/.aws/credentials]/Concat_file[/root/.aws/credentials]: Failed to generate additional resources using 'generate': Invalid parameter show_diff
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util/errors.rb:60:in `fail'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type.rb:642:in `[]='
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type.rb:2240:in `block in set_parameters'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type.rb:2234:in `each'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type.rb:2234:in `set_parameters'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type.rb:2196:in `initialize'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type/file.rb:400:in `initialize'
==> default: /tmp/vagrant-puppet/modules-41ee50e0bca8a8f9e6ee7d005b41df51/concat/lib/puppet/type/concat_file.rb:205:in `new'
==> default: /tmp/vagrant-puppet/modules-41ee50e0bca8a8f9e6ee7d005b41df51/concat/lib/puppet/type/concat_file.rb:205:in `generate'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:202:in `generate_additional_resources'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:222:in `block in add_dynamically_generated_resources'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:222:in `each'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:222:in `add_dynamically_generated_resources'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:94:in `evaluate'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/resource/catalog.rb:144:in `apply'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:122:in `block in apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:179:in `block in benchmark'
==> default: /opt/ruby/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:178:in `benchmark'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:121:in `apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:179:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:265:in `apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:213:in `main'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:146:in `run_command'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `block (2 levels) in run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:456:in `plugin_hook'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `block in run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:504:in `exit_on_fail'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util/command_line.rb:132:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util/command_line.rb:86:in `execute'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/bin/puppet:4:in `<top (required)>'
==> default: /opt/ruby/bin/puppet:23:in `load'
==> default: /opt/ruby/bin/puppet:23:in `<main>'
==> default: Error: /Stage[main]/Awsads/Awscli::Profile[default]/Concat[/root/.aws/config]/Concat_file[/root/.aws/config]: Failed to generate additional resources using 'generate': Invalid parameter show_diff
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util/errors.rb:60:in `fail'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type.rb:642:in `[]='
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type.rb:2240:in `block in set_parameters'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type.rb:2234:in `each'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type.rb:2234:in `set_parameters'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type.rb:2196:in `initialize'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/type/file.rb:400:in `initialize'
==> default: /tmp/vagrant-puppet/modules-41ee50e0bca8a8f9e6ee7d005b41df51/concat/lib/puppet/type/concat_file.rb:205:in `new'
==> default: /tmp/vagrant-puppet/modules-41ee50e0bca8a8f9e6ee7d005b41df51/concat/lib/puppet/type/concat_file.rb:205:in `generate'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:202:in `generate_additional_resources'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:222:in `block in add_dynamically_generated_resources'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:222:in `each'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:222:in `add_dynamically_generated_resources'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:94:in `evaluate'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/resource/catalog.rb:144:in `apply'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:122:in `block in apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:179:in `block in benchmark'
==> default: /opt/ruby/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:178:in `benchmark'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:121:in `apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:179:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:265:in `apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:213:in `main'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:146:in `run_command'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `block (2 levels) in run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:456:in `plugin_hook'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `block in run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:504:in `exit_on_fail'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util/command_line.rb:132:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util/command_line.rb:86:in `execute'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/bin/puppet:4:in `<top (required)>'
==> default: /opt/ruby/bin/puppet:23:in `load'
==> default: /opt/ruby/bin/puppet:23:in `<main>'
==> default: Info: Applying configuration version '1476402450'
==> default: Debug: /Stage[setup]/before: requires Stage[main]
==> default: Debug: /Stage[runtime]/require: requires Stage[main]
==> default: Debug: /Stage[runtime]/before: requires Stage[setup_infra]
==> default: Debug: /Stage[setup_infra]/before: requires Stage[deploy_infra]
==> default: Debug: /Stage[deploy_infra]/before: requires Stage[setup_app]
==> default: Debug: /Stage[setup_app]/before: requires Stage[deploy_app]
==> default: Debug: /Stage[deploy_app]/before: requires Stage[deploy]
==> default: Debug: /Stage[main]/Awscli/Package[awscli]/require: requires Class[Awscli::Deps]
==> default: Debug: /Stage[main]/Awsads/Awscli::Profile[default]/Concat[/root/.aws/credentials]/Concat_file[/root/.aws/credentials]: Autorequiring Concat_fragment[default-credentials]
==> default: Debug: /Stage[main]/Awsads/Awscli::Profile[default]/Concat[/root/.aws/config]/Concat_file[/root/.aws/config]: Autorequiring Concat_fragment[default-config]
==> default: Debug: /Schedule[daily]: Skipping device resources because running on a host
==> default: Debug: /Schedule[monthly]: Skipping device resources because running on a host
==> default: Debug: /Schedule[hourly]: Skipping device resources because running on a host
==> default: Notice: THIS FUCKING SUCKS
==> default: Notice: /Stage[main]//Notify[THIS FUCKING SUCKS]/message: defined 'message' as 'THIS FUCKING SUCKS'
==> default: Debug: /Stage[main]//Notify[THIS FUCKING SUCKS]: The container Class[Main] will propagate my refresh event
==> default: Debug: Prefetching apt resources for package
==> default: Debug: Executing '/usr/bin/dpkg-query -W --showformat '${Status} ${Package} ${Version}\n''
==> default: Debug: Executing '/usr/bin/dpkg-query -W --showformat '${Status} ${Package} ${Version}\n''
==> default: Debug: /Schedule[never]: Skipping device resources because running on a host
==> default: Debug: /Schedule[weekly]: Skipping device resources because running on a host
==> default: Notice: GOT TO THE CLASS
==> default: Notice: /Stage[main]/Awsads/Notify[GOT TO THE CLASS]/message: defined 'message' as 'GOT TO THE CLASS'
==> default: Debug: /Stage[main]/Awsads/Notify[GOT TO THE CLASS]: The container Class[Awsads] will propagate my refresh event
==> default: Error: /Stage[main]/Awsads/Awscli::Profile[default]/Concat[/root/.aws/credentials]/Concat_file[/root/.aws/credentials]: Failed to generate additional resources using 'eval_generate: undefined method `[]=' for nil:NilClass
==> default: /tmp/vagrant-puppet/modules-41ee50e0bca8a8f9e6ee7d005b41df51/concat/lib/puppet/type/concat_file.rb:212:in `eval_generate'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:151:in `eval_generate'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:380:in `traverse'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:98:in `evaluate'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/resource/catalog.rb:144:in `apply'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:122:in `block in apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:179:in `block in benchmark'
==> default: /opt/ruby/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:178:in `benchmark'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:121:in `apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:179:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:265:in `apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:213:in `main'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:146:in `run_command'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `block (2 levels) in run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:456:in `plugin_hook'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `block in run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:504:in `exit_on_fail'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util/command_line.rb:132:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util/command_line.rb:86:in `execute'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/bin/puppet:4:in `<top (required)>'
==> default: /opt/ruby/bin/puppet:23:in `load'
==> default: /opt/ruby/bin/puppet:23:in `<main>'
==> default: Debug: /Schedule[puppet]: Skipping device resources because running on a host
==> default: Debug: Class[Main]: The container Stage[main] will propagate my refresh event
==> default: Error: /Stage[main]/Awsads/Awscli::Profile[default]/Concat[/root/.aws/config]/Concat_file[/root/.aws/config]: Failed to generate additional resources using 'eval_generate: undefined method `[]=' for nil:NilClass
==> default: /tmp/vagrant-puppet/modules-41ee50e0bca8a8f9e6ee7d005b41df51/concat/lib/puppet/type/concat_file.rb:212:in `eval_generate'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:151:in `eval_generate'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:380:in `traverse'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/transaction.rb:98:in `evaluate'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/resource/catalog.rb:144:in `apply'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:122:in `block in apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:179:in `block in benchmark'
==> default: /opt/ruby/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:178:in `benchmark'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:121:in `apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/configurer.rb:179:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:265:in `apply_catalog'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:213:in `main'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application/apply.rb:146:in `run_command'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `block (2 levels) in run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:456:in `plugin_hook'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `block in run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util.rb:504:in `exit_on_fail'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/application.rb:364:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util/command_line.rb:132:in `run'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/lib/puppet/util/command_line.rb:86:in `execute'
==> default: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.1.1/bin/puppet:4:in `<top (required)>'
==> default: /opt/ruby/bin/puppet:23:in `load'
==> default: /opt/ruby/bin/puppet:23:in `<main>'

**Comment by CarmenAPuccio** [comment]
I figured this out. Your module breaks with the later version of concat apparently. I locked it to the same version in your puppetfile.lock and it works now



forge "https://forgeapi.puppetlabs.com"

mod 'stahnma/epel', '1.0.2'
mod 'puppetlabs-stdlib'
mod 'jdowning-awscli'
mod 'puppetlabs-concat', '1.2.0'
